[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
ml-zoomcamp = "ml_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
